import { SecurityFinding, TimelineItem, ProjectData } from './types';

export const mockSecurityFindings: SecurityFinding[] = [
  {
    id: '1',
    type: 'email',
    severity: 'high',
    file: 'src/components/auth/login.tsx',
    line: 45,
    column: 12,
    content: 'contact@company.com',
    suggestedFix: 'Remove hardcoded email addresses. Use environment variables or configuration files.',
    context: 'const supportEmail = "contact@company.com"; // API support',
  },
  {
    id: '2',
    type: 'api_key',
    severity: 'high',
    file: 'src/config/stripe.ts',
    line: 8,
    column: 28,
    content: 'DEMO_STRIPE_KEY_REDACTED',
    suggestedFix: 'Move API keys to environment variables (STRIPE_SECRET_KEY). Never commit secrets.',
    context: 'const stripeKey = "DEMO_STRIPE_KEY_REDACTED";',
  },
  {
    id: '3',
    type: 'phone',
    severity: 'medium',
    file: 'src/utils/support.ts',
    line: 23,
    column: 15,
    content: '+1-555-123-4567',
    suggestedFix: 'Store phone numbers in secure configuration, not in code comments.',
    context: '// Customer support: +1-555-123-4567',
  },
  {
    id: '4',
    type: 'sql_injection',
    severity: 'high',
    file: 'src/api/users.ts',
    line: 156,
    column: 40,
    content: 'SELECT * FROM users WHERE id = " + userId',
    suggestedFix: 'Use parameterized queries. Replace with prepared statements or ORM.',
    context: 'const query = "SELECT * FROM users WHERE id = " + userId;',
  },
  {
    id: '5',
    type: 'email',
    severity: 'medium',
    file: 'src/middleware/auth.ts',
    line: 67,
    column: 22,
    content: 'admin@example.com',
    suggestedFix: 'Move admin emails to environment configuration.',
    context: 'if (userEmail === "admin@example.com") {',
  },
  {
    id: '6',
    type: 'api_key',
    severity: 'high',
    file: '.env.example',
    line: 3,
    column: 1,
    content: 'OPENAI_API_KEY=DEMO_OPENAI_KEY_REDACTED',
    suggestedFix: 'Use actual .env file, not .env.example. Example files should show structure only.',
    context: 'OPENAI_API_KEY=DEMO_OPENAI_KEY_REDACTED',
  },
  {
    id: '7',
    type: 'sql_injection',
    severity: 'medium',
    file: 'src/db/queries.ts',
    line: 89,
    column: 25,
    content: 'const filter = `WHERE name LIKE \'%${searchTerm}%\'`',
    suggestedFix: 'Use parameterized queries with placeholders (?). Sanitize all user inputs.',
    context: 'const filter = `WHERE name LIKE \'%${searchTerm}%\'`;',
  },
  {
    id: '8',
    type: 'phone',
    severity: 'low',
    file: 'src/constants/support.ts',
    line: 12,
    column: 8,
    content: '+44-20-7946-0958',
    suggestedFix: 'Consider storing contact information separately from source code.',
    context: 'export const UK_SUPPORT_PHONE = "+44-20-7946-0958";',
  },
];

export const mockTimelineItems: TimelineItem[] = [
  {
    id: 'timeline-1',
    title: 'Added Payment Integration',
    description: 'Integrated Stripe payment processing for checkout flow',
    timestamp: new Date('2024-12-28T14:30:00'),
    category: 'feature',
  },
  {
    id: 'timeline-2',
    title: 'Security Audit Completed',
    description: 'Ran full security scan on codebase. Found 8 issues.',
    timestamp: new Date('2024-12-25T09:15:00'),
    category: 'security',
  },
  {
    id: 'timeline-3',
    title: 'Refactored Authentication',
    description: 'Updated auth flow to use OAuth 2.0 with JWT tokens',
    timestamp: new Date('2024-12-22T16:45:00'),
    category: 'refactor',
  },
  {
    id: 'timeline-4',
    title: 'Database Migration',
    description: 'Migrated user data to new PostgreSQL instance',
    timestamp: new Date('2024-12-20T11:20:00'),
    category: 'feature',
  },
  {
    id: 'timeline-5',
    title: 'Added Rate Limiting',
    description: 'Implemented API rate limiting to prevent abuse',
    timestamp: new Date('2024-12-18T13:00:00'),
    category: 'security',
  },
];

export const mockProjectData: ProjectData = {
  name: 'AI Project Intelligence Platform',
  type: 'SaaS Application',
  modules: ['Authentication', 'Payment Processing', 'User Dashboard', 'Security Auditor', 'API Gateway'],
  dataFlow: 'Client -> Next.js Server -> PostgreSQL Database -> Third-party APIs',
  securityScore: 42,
  findings: mockSecurityFindings,
  memoryItems: mockTimelineItems,
};
